### ISSUE TITLE
Trouble building on Windows

### ISSUE THREAD

**Issue by ghost** [rustwasm/rust-webpack-template#171]
### Summary

I have created a new package using the following command: npm init rust-webpack <project name>.

Whenever I tried to build my project the build fails with an error I'm not sure what it means:

```
λ npm run build

> rust-webpack-template@0.1.0 build C:\Users\Lucas\Projects\online-minesweeper
> rimraf dist pkg && webpack

�  Checking for wasm-pack...

ℹ️  Installing wasm-pack

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rust-webpack-template@0.1.0 build: `rimraf dist pkg && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rust-webpack-template@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lucas\AppData\Roaming\npm-cache\_logs\2020-08-08T13_34_47_034Z-debug.log

```

### Additional Details

Nothing I can think of.

**Comment by lukbukkit** [comment]
You have to install [wasm-pack](https://rustwasm.github.io/wasm-pack/installer/) to build your Rust application
