### ISSUE TITLE
Cant get template downloaded

### ISSUE THREAD

**Issue by OriUrano** [rustwasm/rust-webpack-template#183]
Im trying to download this template, but im getting this error:

```
PS C:\Code\Projects> npm init rust-webpack wasm-test
C:\Users\dibob\AppData\Local\npm-cache\_npx\6f943a42ba5b2fe2\node_modules\create-rust-webpack\.bin\create-rust-webpack.js:13
    throw output.error;   
    ^
   
Error: spawnSync git ENOENT
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:812:24)
    at run (C:\Users\dibob\AppData\Local\npm-cache\_npx\6f943a42ba5b2fe2\node_modules\create-rust-webpack\.bin\create-rust-webpack.js:10:18)
    at Object.<anonymous> (C:\Users\dibob\AppData\Local\npm-cache\_npx\6f943a42ba5b2fe2\node_modules\create-rust-webpack\.bin\create-rust-webpack.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync git',
  path: 'git',
  spawnargs: [
    'clone',
    '--no-tags',
    '--depth',
    '1',
    'https://github.com/rustwasm/rust-webpack-template.git',
    'wasm-test\\git-clone'
  ]
}
npm ERR! code 1
npm ERR! path C:\Code\Projects
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-rust-webpack "wasm-test"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dibob\AppData\Local\npm-cache\_logs\2022-03-23T22_35_24_992Z-debug.log
```

Can someone please help me?

**Comment by simon-ritchie** [comment]
Maybe related:

https://github.com/rustwasm/rust-webpack-template/issues/171
